[package]
name = "network"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7.0"
socketioxide = "0.17.0"
tower-http = { version = "0.5", features = ["cors"] }
db = { path = "../db" }
axum-client-ip = "1.1.3"
